[package]
name = "cctoy"
version = "0.2.4"
authors = ["Christian Mauduit (ufoot) <ufoot@ufoot.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.9.1"
withgdnative = { path = "../withgdnative" }

[lib]
crate-type = ["cdylib", "staticlib"]
