[package]
name = "cctoy"
version = "0.3.1"
authors = ["Christian Mauduit (ufoot) <ufoot@ufoot.org>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
godot = { version = "0.5.5", features = ["experimental-wasm"] }
withgodot = { path = "../withgodot" }

[features]
# Web build without thread support (see grcc-lib-wasm-nothreads)
nothreads = ["withgodot/nothreads", "godot/experimental-wasm-nothreads"]

[lib]
crate-type = ["cdylib"]
