[package]
name = "cctoy"
version = "0.3.0"
authors = ["Christian Mauduit (ufoot) <ufoot@ufoot.org>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
godot = "0.4.5"
withgodot = { path = "../withgodot" }

[lib]
crate-type = ["cdylib"]
